development: &default
  :namespace: <%= ENV['SIDEKIQ_NAMESPACE'] %>
  :pidfile: tmp/pids/sidekiq.pid
  :expires: 120
  :concurrency: 25
  :queues:
    - default
    - [sentry, 1]

production:
  <<: *default

test:
  <<: *default
